# Generated by Django 2.0.6 on 2018-07-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='to_friend',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='from_friend',
            new_name='user',
        ),
    ]
